# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QiChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QiChat

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'GoogleMaps'
pod 'GooglePlaces'

  target 'QiChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QiChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
